apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: always-cron
  name: always-cron
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: always-cron
    spec:
      containers:
      - args:
        - cron
        image: cron
        name: always-cron
        ports:
        - containerPort: 5544
        resources: {}
      hostname: always-cron
      restartPolicy: Always
status: {}
