apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: apache
  name: apache
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apache
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: ku
        image: gcr.io/emil-242911/apache:0.3
        name: apache
        ports:
        - containerPort: 80
        resources: {}
      hostname: apache
      restartPolicy: Always
status: {}
