apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: ku
        - name: MYSQL_PASSWORD
          value: kudbpassword
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_USER
          value: ku
        image: gcr.io/emil-242911/db:0.1
        name: db
        ports:
        - containerPort: 3306
        resources: {}
      hostname: db
      restartPolicy: Always
status: {}
