apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: obvius
  name: obvius
spec:
  containers:
  - image: obvius
    name: obvius
    resources: {}
  hostname: obvius
  restartPolicy: Never
status: {}
