apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "default"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
